spring.datasource.url=jdbc:postgresql://localhost:5432/medicare_db
spring.datasource.username=postgres
spring.datasource.password=qwerty

jwt.secret=medicare_secret_key_change_this_in_production_must_be_at_least_256_bits_long
jwt.expiration=86400000

server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.medicare=DEBUG